# Numpy의 소개
NumPy(Numerical Python)는 파이썬에서 과학적 계산을 위한 핵심 라이브러리이다. NumPy는 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다. 하지만 NumPy 자체로는 고수준의 데이터 분석 기능을 제공하지 않기 때문에 NumPy 배열과 배열 기반 컴퓨팅의 이해를 통해 pandas와 같은 도구를 좀 더 효율적으로 사용하는 것이 필요하다.

### ndarry 생성
array 함수를 사용하여 배열 생성하기

In [1]:
import numpy as np

In [3]:
# ndarray를 생성
arr = np.array([1,2,3,4])

In [4]:
print(arr)

[1 2 3 4]


In [5]:
type(arr)

numpy.ndarray

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.empty((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ndarray 배열의 모양, 차수, 데이터 타입 확인하기

In [11]:
arr = np.array([[1,2,3],[4,5,6]])

In [12]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
arr.shape

(2, 3)

In [14]:
arr.ndim

2

In [15]:
arr.dtype

dtype('int32')

In [16]:
arr_float = arr.astype(np.float64)

In [19]:
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
arr_float.dtype

dtype('float64')

In [21]:
arr.dtype

dtype('int32')

In [26]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

# arr3 = arr1 + arr2
# arr3 = np.add(arr1, arr2)
# arr3 = arr1 * arr2
arr3 = np.multiply(arr1, arr2)
print(arr3)

[[ 5 12]
 [21 32]]


Numpy 배열의 연산은 연산자 (+,-,*,/)나 함수(add, subtract, multiply, divide)로 가능하다.

### ndarray 배열 슬라이싱 하기

ndarray 배열 슬라이싱 하기

In [28]:
# 배열 슬라이싱
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [30]:
arr.shape

(3, 3)

In [35]:
arr_int = np.arange(10)
print(arr_int[0:8:2])

[0 2 4 6]


In [36]:
print(arr[0,2])

3


In [39]:
arr = np.array([[1,2,3],[4,5,6]])

In [41]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]]


In [42]:
print(arr[idx])

[4 5 6]


In [43]:
redwine = np.loadtxt(fname='samples/winequality-red.csv', 
                      delimiter=';', skiprows=1)

In [44]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [45]:
redwine.shape

(1599, 12)

In [46]:
type(redwine)

numpy.ndarray

In [47]:
print(redwine.sum())

152084.78194


In [48]:
print(redwine.mean())

7.926036165311652


In [51]:
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [52]:
print(redwine[:,0].mean())

8.31963727329581
